# -*- coding: utf-8 -*-
"""iterasi sederhana

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AY-FevZB06IDKiABj7ZJMSZAPAy8NDiX
"""

import math

# function operatorPetama - operator kedua -
def a(x):
    return koefisienPertama*x**pangkatPertama - koefisienKedua*x**pangkatKedua - konstanta

def g(x):
    return ((koefisienKedua*x**pangkatKedua + konstanta)**(1/pangkatPertama))/koefisienPertama

# function operatorPetama + operator kedua +
def b(x):
    return koefisienPertama*x**pangkatPertama + koefisienKedua*x**pangkatKedua + konstanta

def h(x):
    return ((-koefisienKedua*x**pangkatKedua + konstanta)**(1/pangkatPertama))/koefisienPertama

# function operatorPetama - operator kedua +
def c(x):
    return koefisienPertama*x**pangkatPertama - koefisienKedua*x**pangkatKedua + konstanta

def i(x):
    return ((koefisienKedua*x**pangkatKedua + konstanta)**(1/pangkatPertama))/koefisienPertama

#input data
koefisienPertama=float(input('masukkan koeisien pertama: '))
pangkatPertama=float(input('masukkan pangkat pertama: '))
operatorPertama=input('masukkan operator pertama +/- :')
koefisienKedua=float(input('masukkan koeisien Kedua: '))
pangkatKedua=float(input('masukkan pangkat Kedua: '))
operatorKedua=input('masukkan operator Kedua +/-: ')
konstanta=float(input('masukkan konstanta:'))
x0 = float(input('masukkan nilai awal: '))
e = float(input('toleransi Error: '))
N = int(input('Maximum iterasi: '))
if(operatorPertama=='-' and operatorKedua=='-'):  
    print('\n\nIterasi Sederhana')
    step = 1
    flag = 1
    condition = True
    while condition:      
        x1 = g(x0)
        print('Iteration-%d, g(x1) = %0.6f and f(x1) = %0.6f' % (step, x1, a(x1)))
        x0 = x1

        step = step + 1
        
        if step > N:
            flag=0
            break
        
        condition = abs(a(x1)) > e

    if flag==1:
        print('\nRequired root is: %0.8f' % x1)
    else:
        print('\nNot Convergent.')

if(operatorPertama=='+' and operatorKedua=='+'):  
    print('\n\nIterasi Sederhana')
    step = 1
    flag = 1
    condition = True
    while condition:      
        x1 = h(x0)
        print('Iteration-%d, g(x1) = %0.6f and f(x1) = %0.6f' % (step, x1,c(x1)))
        x0 = x1

        step = step + 1
        
        if step > N:
            flag=0
            break
        
        condition = abs(c(x1)) > e

    if flag==1:
        print('\nRequired root is: %0.8f' % x1)
    else:
        print('\nNot Convergent.')

if(operatorPertama=='-' and operatorKedua=='+'):  
    print('\n\nIterasi Sederhana')
    step = 1
    flag = 1
    condition = True
    while condition:      
        x1 = i(x0)
        print('Iteration-%d, g(x1) = %0.6f and f(x1) = %0.6f' % (step, x1, c(x1)))
        x0 = x1

        step = step + 1
        
        if step > N:
            flag=0
            break
        
        condition = abs(c(x1)) > e

    if flag==1:
        print('\n: %0.8f' % x1)
    else:
        print('\ntidak konvergen Convergent.')

