# -*- coding: utf-8 -*-
"""iterasi _simple

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nSgzl8_esPXaua3rkf0ut-F7drhbcgw2

# Iterasi Sederhana
Oleh kelompok 2

1.

2.

3.

4.

5.

6.
"""

from math import *

"""# from math import *
kode ini berfungsi untuk mengimpor/mengambil fungsi math dari phyton sendiri kemudian mengambil operator arimatika pangkat *
"""

from math import *

def a(x):
    return (eval(inputfx))

def g(x):
    return (eval(inputgx))

#input data
inputfx=str(input('masukkan f(x): '))
inputgx=str(input('masukkan g(x): '))
x0 = float(input('masukkan nilai awal: '))
e = float(input('toleransi Error: '))
N = int(input('Maximum iterasi: '))
print('\n\nIterasi Sederhana')
step = 1
flag = 1
condition = True
while condition:      
    x1 = g(x0)
    print('Iteration-%d, g(x1) = %0.6f and f(x1) = %0.6f' % (step, x1, a(x1)))
    x0 = x1

    step = step + 1
        
    if step > N:
         flag=0
         break
        
    condition = abs(a(x1)) > e

if flag==1:
    print('\nRequired root is: %0.8f' % x1)
else:
    print('\nNot Convergent.')